### PR TITLE
Add Flake8 Code Checker

### PR DESCRIPTION
**Pull request by dc-aichara**
Scope of PR:
1. Add [flake8](https://flake8.pycqa.org/en/latest/) to repository. 
2. Fix flake8 errors.
3. Add flake8 to workflow pipeline.

### CODE REVIEW

**Comment by R1j1t** [comment]
Thanks, I will have a look and merge it today!

**Comment by R1j1t** [comment]
I made a few changes to the flake8:
1. added test cases to flake8 check
2. updated the action based on this [starter workflow from github](https://github.com/actions/starter-workflows/blob/6933b58bfef81ee5fb3442e2a6fa4b3774c1eaf4/ci/python-package.yml)

If you have any comments please let me know.

**Comment by dc-aichara** [comment]
Thanks @R1j1t . Looks good to me.

**Comment by R1j1t** [comment]
I am very thankful @dc-aichara! When I started this project, I was not sure if people will like it, let alone getting contributions.

**Pull request merged**
